const path = require("path");
const esbuild = require("esbuild");

const root = path.resolve(__dirname, "..");

esbuild.buildSync({
  entryPoints: [path.join(root, "src/main.js")],
  bundle: true,
  external: ["obsidian"],
  format: "cjs",
  target: "es2018",
  outfile: path.join(root, "main.js"),
  banner: {
    js: "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD. Edit src/ and run `npm run build`. */"
  },
  logLevel: "info"
});
